## Découverte de Numpy
### Introduction à Numpy

**ndarray**

In [1]:
import numpy as np

In [2]:
vector = np.array([3, 4, 17, 65])

In [3]:
print(vector)

[ 3  4 17 65]


In [5]:
matrix = np.array([[2, 5, 15], [20, 50, 30], [34, 99, 45]])

In [6]:
print(matrix)

[[ 2  5 15]
 [20 50 30]
 [34 99 45]]


In [7]:
vector = np.array([10, 20, 30])
print(vector)

[10 20 30]


In [9]:
matrix = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
print(matrix)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


### Taille d'un tableau

**ndarray.shape**

In [13]:
matrix_shape = matrix.shape

In [14]:
vector_shape = vector.shape

In [16]:
print(f"la taille du vecteur {vector} est {vector_shape}")

la taille du vecteur [10 20 30] est (3,)


In [19]:
print(f"la taille de la matrice {matrix} est {matrix_shape}")

la taille de la matrice [[ 5 10 15]
 [20 25 30]
 [35 40 45]] est (3, 3)


### Lire un dataset avec Numpy

In [21]:
# Fonction Numpy pour lire un dataset: numpy.genfromtxt(fichier csv, delimiter="" )

In [22]:
import numpy as np

world_alcohol = np.genfromtxt('world-alcohol.csv', delimiter=',')

print(f"le type du tableau world_alcohol est {type(world_alcohol)}")

le type du tableau world_alcohol est <class 'numpy.ndarray'>


#### Digression sur 'type()'

In [29]:
type(3) == 'Int'

False

In [27]:
type(type(3))

type

In [26]:
type(3) == "<class 'int'>"

False

In [30]:
type(3)

int

### Les types de données avec Numpy

In [31]:
# bool, int, float et string

In [ ]:
# numpy.dtype()

In [32]:
matrix.dtype

dtype('int64')

In [34]:
world_alcohol_dtype = world_alcohol.dtype

In [35]:
print(f"le type de données dans notre tableau world_alcohol est {world_alcohol_dtype}")

le type de données dans notre tableau world_alcohol est float64


### Afficher correctement les données

In [36]:
world_alcohol

array([[      nan,       nan,       nan,       nan,       nan],
       [1.986e+03,       nan,       nan,       nan, 0.000e+00],
       [1.986e+03,       nan,       nan,       nan, 5.000e-01],
       ...,
       [1.986e+03,       nan,       nan,       nan, 2.540e+00],
       [1.987e+03,       nan,       nan,       nan, 0.000e+00],
       [1.986e+03,       nan,       nan,       nan, 5.150e+00]])

In [37]:
world_alcohol = np.genfromtxt('world-alcohol.csv', delimiter=',', dtype='U75')
world_alcohol

array([['Year', 'WHO region', 'Country', 'Beverage Types',
        'Display Value'],
       ['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

In [38]:
world_alcohol = np.genfromtxt('world-alcohol.csv', delimiter=',', dtype='U75', skip_header=1)
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

### Extraire une valeur depuis un tableau Numpy

In [39]:
print(vector[0])

10


In [40]:
print(matrix[0])

[ 5 10 15]


In [41]:
print(matrix[0][2])

15


In [44]:
print(matrix[0, 2])

15


In [45]:
ivoire_1985 = world_alcohol[2, 4]
second_country = world_alcohol[1, 2]
print(f"la consommation de {world_alcohol[2][3]} pour un habitant de {world_alcohol[2][2]} est {ivoire_1985} l/an")
print(f"le nom du pays de la seconde ligne est {second_country}")

la consommation de Wine pour un habitant de Cte d'Ivoire est 1.62 l/an
le nom du pays de la seconde ligne est Uruguay


### Extraire un vecteur de valeurs depuis un tableau Numpy

In [47]:
vector[0:2]

array([10, 20])

In [48]:
matrix[:,1]

array([10, 25, 40])

In [49]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [50]:
matrix[2,:]

array([35, 40, 45])

In [51]:
matrix[1:3,1]

array([25, 40])

In [55]:
# toute la 3e colonne de world_alcohol
countries = world_alcohol[:,2]

In [57]:
print(countries)
countries

['Viet Nam' 'Uruguay' "Cte d'Ivoire" ... 'Switzerland' 'Papua New Guinea'
 'Swaziland']


array(['Viet Nam', 'Uruguay', "Cte d'Ivoire", ..., 'Switzerland',
       'Papua New Guinea', 'Swaziland'], dtype='<U75')

In [54]:
# l'ensemble de la 5e colonne de world_alcohol
alcohol_consumption = world_alcohol[:,4]
alcohol_consumption

array(['0', '0.5', '1.62', ..., '2.54', '0', '5.15'], dtype='<U75')

### Extraire un tableau de valeurs depuis un tableau Numpy

In [58]:
matrix[:,0:2]

array([[ 5, 10],
       [20, 25],
       [35, 40]])

In [59]:
matrix[1:3,:]

array([[20, 25, 30],
       [35, 40, 45]])

In [60]:
matrix[1:3,0:2]

array([[20, 25],
       [35, 40]])

In [61]:
first_two_columns = world_alcohol[:,0:2] # toutes les lignes des deux premières colonnes
first_two_columns

array([['1986', 'Western Pacific'],
       ['1986', 'Americas'],
       ['1985', 'Africa'],
       ...,
       ['1986', 'Europe'],
       ['1987', 'Western Pacific'],
       ['1986', 'Africa']], dtype='<U75')

In [64]:
# les dix premières lignes de la première colonne
first_ten_years = world_alcohol[:10,:1]
first_ten_years

array([['1986'],
       ['1986'],
       ['1985'],
       ['1986'],
       ['1987'],
       ['1987'],
       ['1987'],
       ['1985'],
       ['1986'],
       ['1984']], dtype='<U75')

In [65]:
# les dix premières lignes de toutes les colonnes
first_ten_rows = world_alcohol[:10,:]
first_ten_rows

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ['1986', 'Americas', 'Colombia', 'Beer', '4.27'],
       ['1987', 'Americas', 'Saint Kitts and Nevis', 'Beer', '1.98'],
       ['1987', 'Americas', 'Guatemala', 'Other', '0'],
       ['1987', 'Africa', 'Mauritius', 'Wine', '0.13'],
       ['1985', 'Africa', 'Angola', 'Spirits', '0.39'],
       ['1986', 'Americas', 'Antigua and Barbuda', 'Spirits', '1.55'],
       ['1984', 'Africa', 'Nigeria', 'Other', '6.1']], dtype='<U75')

In [66]:
# les vingt premières lignes des colonnes d'indice 1 et 2
first_twenty_regions = world_alcohol[:20,1:3]
first_twenty_regions

array([['Western Pacific', 'Viet Nam'],
       ['Americas', 'Uruguay'],
       ['Africa', "Cte d'Ivoire"],
       ['Americas', 'Colombia'],
       ['Americas', 'Saint Kitts and Nevis'],
       ['Americas', 'Guatemala'],
       ['Africa', 'Mauritius'],
       ['Africa', 'Angola'],
       ['Americas', 'Antigua and Barbuda'],
       ['Africa', 'Nigeria'],
       ['Africa', 'Botswana'],
       ['Americas', 'Guatemala'],
       ['Western Pacific', "Lao People's Democratic Republic"],
       ['Eastern Mediterranean', 'Afghanistan'],
       ['Western Pacific', 'Viet Nam'],
       ['Africa', 'Guinea-Bissau'],
       ['Americas', 'Costa Rica'],
       ['Africa', 'Seychelles'],
       ['Europe', 'Norway'],
       ['Africa', 'Kenya']], dtype='<U75')

In [67]:
len(first_twenty_regions)

20